package taldawasm:http

interface http-endpoint-types {
    use wasi:http/types.{method, error, status-code}
    type headers = list<tuple<string, string>>
    type body = list<u8>
    type path = string

    record request {
      path: path,
      method: method,
      headers: headers,
      body: option<body>
    }

    record response {
      status-code: status-code,
      headers: option<headers>,
      body: option<body>
    }
}
