interface http-endpoint {
    use http-types.{request, response, error}
    handle-request: func(request: request) -> result<response, error>
}

world http-endpoint-component {
    import http-outgoing
    export http-endpoint
}