[package]
name = "wasm_echo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ['cdylib']

[dependencies]
http_wrapper = { path = "../../http_wrapper" }
structs = { path = "../../structs" }
