[package]
name = "http-endpoint-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[lib]
crate-type = ['cdylib']

[dependencies]
taldawasm = { path = "../../" }
wit-bindgen = "0.9.0"
