[package]
name = "http-endpoint"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
wit-bindgen = { workspace = true }
http = { workspace = true }
bytes = "1"
anyhow = "1"